create sequence HIBERNATE_SEQUENCE start with 1 increment by 1;

create table T_PERSON (
    ID number(10) not null,
    NAME varchar2(64) not null,
    COMMENTS varchar2(128),
    constraint PK_PERSON primary key (ID)
);

create table T_PERSON_AUD (
    ID number(10) not null,
    NAME varchar2(64),
    COMMENTS varchar2(128),
    NAME_MOD number(1),
    COMMENTS_MOD number(1),
    REV number(10) not null,
    REVTYPE number(1),
    constraint PK_PERSON_AUD primary key (ID, REV)
);

create table REVINFO (
    REV number(10) generated by default as identity (start with 1),
    REVTSTMP number(16),
    USERNAME varchar2(16),
    constraint PK_REVINFO primary key (REV)
);
